### ISSUE TITLE
Use of byref in Migrations branch

### ISSUE THREAD

**Issue by cartermp** [bricelam/EFCore.FSharp#18]
This was brought to my attention in this thread: https://forums.fsharp.org/t/how-to-work-with-byref-and-pipe-operator/417/7

In the migrations branch, it appears there is usage of `byref`. Of that, there are 14 places where that usage is invalid; i.e., it produces code that _may_ run, but is not necessarily _going_ to run. These seem to all be of the following variety:

```fsharp
let foo (x: int byref) s =
    x <- x + 1
    printfn "%s %d" s x

let mutable x = 0

"hello" |> foo &x
```

This is explicitly disallowed, because `|>` is a generic function. It is not allowable to parameterize a type with a `byref`, i.e., `foo<byref<Bar>>`, yet this would occur if it were allowed.

So, there are two options here:

1. Rewrite the 14 calls where a `"hello" |> foo &x` equivalent is made to `foo &x "hello"`, which will not attempt to specialize `|>` to a `byref<Foo>`
2. Use a `ref` cell.

Both are equally as invasive, though I would say that a `ref` cell is probably easier. For example, this:

```fsharp
    let private prependLine (addLineBreak: bool byref) (text:string) (sb:IndentedStringBuilder) =
        if addLineBreak then
            sb |> appendEmptyLine |> ignore
        else
            addLineBreak <- true

        sb |> append text |> ignore

    let appendLines (lines: string seq) skipFinalNewLine (sb:IndentedStringBuilder) =

        let mutable addLineBreak = false

        lines |> Seq.iter(fun l -> sb |> prependLine &addLineBreak l)

        if skipFinalNewLine then
            sb
        else
            sb |> appendEmptyLine
```

Becomes this:

```fsharp
    let private prependLine (addLineBreak: bool ref) (text:string) (sb:IndentedStringBuilder) =
        if addLineBreak.Value then
            sb |> appendEmptyLine |> ignore
        else
            addLineBreak := true

        sb |> append text |> ignore

    let appendLines (lines: string seq) skipFinalNewLine (sb:IndentedStringBuilder) =

        let addLineBreak = ref false

        lines |> Seq.iter(fun l -> sb |> prependLine addLineBreak l)

        if skipFinalNewLine then
            sb
        else
            sb |> appendEmptyLine
```

As far as I can tell, the other places this pattern is used could pass a reference cell instead, but a rewrite to not use pipelines with `byref`s is also possible.

**Comment by simontaite** [comment]
Hi @cartermp 
Thanks for this, will update to remove usages of `byref`

**Comment by cartermp** [comment]
Well, perhaps `byref` is more appropriate (depending on whichever is less invasive). There's also technically less overhead, since it's just a pointer, whereas a ref cell is an F# record that contains a mutable value inside. But it would mean that some of the pipelining that is done won't compile with F# 4.5.

**Comment by simontaite** [comment]
Latest commits on migration-support branch update code to use `ref` instead of `byref` or drop usage of either
