### ISSUE TITLE
Migrations support

### ISSUE THREAD

**Issue by bricelam** [bricelam/EFCore.FSharp#2]
We'll need to implement `IMigrationsCodeGenerator` to support adding a new migration.

**Comment by bricelam** [comment]
cc @cartermp (FYI so you can track F# support for this in EF Core)

**Comment by bricelam** [comment]
You may use the C# version as a reference implementation. See [CSharpMigrationsGenerator](https://github.com/aspnet/EntityFrameworkCore/blob/release/2.1/src/EFCore.Design/Migrations/Design/CSharpMigrationsGenerator.cs) and its subcomponents [CSharpMigrationOperationGenerator](https://github.com/aspnet/EntityFrameworkCore/blob/release/2.1/src/EFCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs) and [CSharpSnapshotGenerator](https://github.com/aspnet/EntityFrameworkCore/blob/release/2.1/src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs).

**Comment by EelcoMulder** [comment]
I would like to use this, so can I help with something?

**Comment by simontaite** [comment]
@bricelam I'm working on wiring together the different parts of a migration
In C# we get <timestamp>_<MigrationName>.cs and <timestamp>_<MigrationName>.Designer.cs created as partial classes

F# doesn't support partial classes and an override can't be used in a type augmentation. Is there any design reason behind the decision to create migrations as partial classes?
Would there be a downside to creating a single Migration that combines the two?

**Comment by simontaite** [comment]
Hi @EelcoMulder 
A lot of the groundwork has been done at this stage but any assistance is always welcome!
At the moment, one issue I'm trying to find a solution for is how to handle adding the generated migrations to the .fsproj file in the correct location for compliation

Any ideas on how this could be approached would be very much appreciated!

**Comment by EelcoMulder** [comment]
@simontaite I think the C# approach should work here too, looking at https://github.com/odytrice/PluralsightDownloads/tree/master/PlaybyPlayEFCore10/FSharp/myapi

**Comment by bricelam** [comment]
> Would there be a downside to creating a single Migration that combines the two?

No, we really just use the `*.Designer.cs` files as a *don't touch this code* marker, but there are plenty of other ways to communicate that.

We might need to file an issue on EF to not write the designer file if the contents are empty.

**Comment by simontaite** [comment]
Awesome! Shall have a look at how to pass the necessary parameters from both methods to one, hopefully will still be able to use the `MigrationsCodeGenerator` base class

Copying everything from the Designer file to the other works for building but `dotnet ef migrations script` throws an error, both normally and trying to create the context via an `IDesignTimeDbContextFactory`

```
System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.ScriptMigration(String fromMigration, String toMigration, Boolean idempotent, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScriptMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
No parameterless constructor defined for this object.
```

Not sure yet if this is something I'm missing in how things are configured or if EF is having issues with record types, although I know that it supports constructors with parameters [as of 2.1](https://docs.microsoft.com/en-us/ef/core/modeling/constructors)

On a related note, I notice some of the API signatures have changed in 2.1.0-preview2, `ICSharpDbContextGenerator.WriteCode` for instance
Should we be developing against preview2?

**Comment by bricelam** [comment]
That error is complaining about the `DbContext` constructor. See [Design-time DbContext Creation](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dbcontext-creation)

**Comment by simontaite** [comment]
Thanks, will look into that and hopefully get a fully working migration soon

For automatically adding migration files to the fsproj, we may be able to utilise https://github.com/fsprojects/Mechanic

**Comment by simontaite** [comment]
Also, will keep an eye on https://github.com/Microsoft/visualfsharp/pull/4499
If this make it into the language soon it would simplify column definition in `CreateTableOperation` a lot

**Comment by dsyme** [comment]
@simontaite It would be really great if you could trial https://github.com/Microsoft/visualfsharp/pull/4499 to see if it works for this scenario. Validating that language addition for a few real-world uses of anonymous types by .NET frameworks is one of the remaining things needed to get it accepted .

**Comment by simontaite** [comment]
Looks like I may have to reimplement `MigrationsScaffolder` after all. Once all the migration is moved to a  single file it generates a migration script, still a few bits to do but it's nice to see it creating the `CREATE TABLE` script correctly with indexes and keys

The population of __EFMigrationsHistory isn't quite correct though, it's not writing the values to SQL as string literals
```
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (20180315153728_InitialCreate, 2.1.0-preview2-30335);
```

**Comment by simontaite** [comment]
@dsyme Now that I actually have a migration I can (more or less) trust I'll be looking at trialing Microsoft/visualfsharp#4499 in the next day or two

**Comment by simontaite** [comment]
@dsyme A migration builds correctly with anon types in VS2017
I can't build or script the migration through the command line by running `dotnet ef` as I have been unable to correctly use the EF Core build from [dsyme/visualfsharp/anon-1](/dsyme/visualfsharp/tree/anon-1) from the command line

**Comment by dsyme** [comment]
> @dsyme A migration builds correctly with anon types in VS2017

> I can't build or script the migration through the command line by running dotnet ef as I have been unable to correctly use the EF Core build from dsyme/visualfsharp/anon-1 from the command line

Do you mean you haven't been able to use the freshly built F# compiler from that branch? Setting `<FscToolPath>` to `c:\Git\visualfsharp\debug\net40\bin` (or whatever) in a PropertyGroup may help with that?

Or is the problem picking up a new FSharp.Core?  If so use an explicit `<Reference>`?

**Comment by simontaite** [comment]
I've set FscToolPath, when I try running `dotnet build` I get the following
```
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for C:\src\MigrationTest\MigrationTest.fsproj...
  Generating MSBuild file C:\src\MigrationTest\obj\MigrationTest.fsproj.nuget.g.props.
  Restore completed in 1.17 sec for C:\src\MigrationTest\MigrationTest.fsproj.
C:\Program Files\dotnet\sdk\2.1.300\FSharp\Microsoft.FSharp.Targets(263,9): error MSB6004: The specified task executable location "C:\src\visualfsharp\release\net40\bin\RunFsc.cmd" is invalid. [C:\src\MigrationTest\MigrationTest.fsproj]

Build FAILED.

C:\Program Files\dotnet\sdk\2.1.300\FSharp\Microsoft.FSharp.Targets(263,9): error MSB6004: The specified task executable location "C:\src\visualfsharp\release\net40\bin\RunFsc.cmd" is invalid. [C:\src\MigrationTest\MigrationTest.fsproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:11.24
```

I can build and create an EF migration using the normal .NET Core installation
I can then comment out the types created for migrations like 

```fsharp
type private StudentsTable = {
    Id: OperationBuilder<AddColumnOperation>
    LastName: OperationBuilder<AddColumnOperation>
    FirstName: OperationBuilder<AddColumnOperation>
    EnrollmentDate: OperationBuilder<AddColumnOperation>
}
```

Setting the FscToolPath then allows me to build in VS2017 with anon types.
But trying to build using `dotnet build` still fails

I've ran .\src\buildfromsource.cmd to build the .NET Core compiler and referenced the built Microsoft.FSharp.Compiler.nupkg but I still get the original error message above

Essentially I can use the built compiler from VS but not through the dotnet CLI

**Comment by dsyme** [comment]
Ah, I think you need to set both FscToolPath and 

    <FscToolExe>fsc.exe</FscToolExe>

**Comment by simontaite** [comment]
That's it, thank you very much!
Builds and creates a valid migration script!

**Comment by greenboxal** [comment]
What's the current status on this? We're going to use EFCore + FSharp a lot here. If there's anything pending in order to be 100%, we can help.

**Comment by albertwoo** [comment]
I tried to build this project and reference it but still not able to do: dotnet ef migrations add Test

**Comment by greenboxal** [comment]
I got it working, had to do a couple fixes in order to get Npgsql working. Will send a PR soon, basically indentation errors and missing namespaces.

**Comment by simontaite** [comment]
Awesome! Thanks very much. I'm afraid I haven't been able to do much on this project over the last while due to some family matters but hoping to be able to get back to working more on it soon
Any PRs to help fix issues or add functionality is always welcome!

Regarding getting to be 100% I would like to push on adding tests to mirror what's in [EntityFramework](https://github.com/aspnet/EntityFrameworkCore/tree/release/2.2/test/EFCore.Design.Tests/Migrations)  to try ensure correctness of what we have so far

After that want to start extending it to be able to ensure things like option types and discriminated unions are mapped in some sensible way

**Comment by EelcoMulder** [comment]
For option types  someone did this: https://blog.bitbadger.solutions/2018/f-sharp-options-with-ef-core.html

**Comment by simontaite** [comment]
Sweet! Thanks for that @EelcoMulder!

**Comment by EelcoMulder** [comment]
I can build this but I have no clue how to use this, I want to contribute but might need some pointers?

**Comment by bricelam** [comment]
@EelcoMulder Should be able to just add a reference to the project/assembly and add the following to project.
``` xml
<Import Project="EFCore.FSharp\build\netstandard2.0\Bricelam.EntityFrameworkCore.FSharp.targets" />
```

**Comment by bricelam** [comment]
Then `dotnet ef migrations add` (or `Add-Migration`) should just work as expected.

**Comment by EelcoMulder** [comment]
Can't get it to work, shouldn't the build.cmd register it as a global tool? I don't think my project uses the correct dotnet ef right now?

**Comment by simontaite** [comment]
@EelcoMulder

It's currently using EF 2.2
build.cmd will output a nupkg file, you can reference it from your own project by adding the output folder to NuGet.config or packet.local depending on which your using

I'm on mobile at the moment but can get an example to you soon

**Comment by simontaite** [comment]
Hi @EelcoMulder 

I've got a simple project on my machine that I can clean up sometime in the next day or two and publish as a working example

In the meantime here's the `paket.dependencies` file
```
source https://api.nuget.org/v3/index.json

nuget FSharp.Core
nuget Microsoft.AspNetCore.App 2.2.0
nuget Npgsql.EntityFrameworkCore.PostgreSQL 2.2.0

# replace path here
source /Users/simon/src/EFCore.FSharp/EFCore.FSharp/bin/Release
nuget Bricelam.EntityFrameworkCore.FSharp 2.2.0-alpha1
```

You can then add a `paket.local` file 
```
# again, change the path to suit
nuget Bricelam.EntityFrameworkCore.FSharp 2.2.0-alpha1 -> source /Users/simon/src/EFCore.FSharp/EFCore.FSharp/bin/Release
```

**Comment by EelcoMulder** [comment]
Will look at it later because it didn't work just yet, so that example would be nice!

**Comment by simontaite** [comment]
Hi @EelcoMulder 
The example is here https://github.com/simontaite/EFCore.FSharp.MigrationTest

Just update the paths in `paket.dependencies` and `paket.local`, and the connection string in `Startup.fs`

It's set up to use Postgresql but should be easy enough to change to SQL Server or any other
Let me know if you need any help with it

**Comment by EelcoMulder** [comment]
Ah thanks, last night I got as far as creating a migration for Sql Server, only couldn't apply the migration just yet. Will take a look at your example!

**Comment by EelcoMulder** [comment]
I got my own example working with Sql Server, awesome!

**Comment by bricelam** [comment]
Where is the migrations implementation at? Can we put an alpha of it up on NuGet.org yet?

**Comment by simontaite** [comment]
Migration support is enough to justify an alpha release

**Comment by EelcoMulder** [comment]
@simontaite are you going to blog about it? I had planned to revisit my own blog about ef core with F#, would love to write a little about this.

**Comment by simontaite** [comment]
Have created #23 to merge these changes

**Comment by simontaite** [comment]
Initial support added
Everything from here on will be a new ticket
