### ISSUE TITLE
Reverse engineer support

### ISSUE THREAD

**Issue by bricelam** [bricelam/EFCore.FSharp#3]
We'll need to implement `IScaffoldingCodeGenerator` to support scaffolding a model from the database.

**Comment by bricelam** [comment]
cc @cartermp (FYI so you can track F# support for this in EF Core)

**Comment by bricelam** [comment]
You may use the C# version as a reference implementation. See [CSharpModelGenerator](https://github.com/aspnet/EntityFrameworkCore/blob/release/2.1/src/EFCore.Design/Scaffolding/Internal/CSharpModelGenerator.cs) and its subcomponents [CSharpDbContextGenerator](https://github.com/aspnet/EntityFrameworkCore/blob/release/2.1/src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs) and [CSharpEntityTypeGenerator](https://github.com/aspnet/EntityFrameworkCore/blob/release/2.1/src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs).

**Comment by isaacabraham** [comment]
Just my two cents. It's been a while since I used EF - if possible, I'd recommend trying to stick with the standard set of types that F# devs use:

* Records
* Immutable fields (although I suppose that all the fields on the record will need to be `mutable` to work with things like change tracking)?
* If possible, discriminated unions for many-types-per-table style relationships (which would be modelled with inheritance in C#).

**Comment by simontaite** [comment]
Depending on interoperability requirements we can create types as either records or class types, maybe depending on an input parameter. This is the approach I'm taking at the moment
Although if interoperability between C# and F# projects is a requirement it would make just as much sense to use C# for EFCore...

Good thinking regarding DU's for many-types-per-table style relationships, hadn't considered these models before but a discriminated union definitely makes the most sense

**Comment by bricelam** [comment]
Where is the reverse engineering implementation at? Can we put an alpha of it up on NuGet.org yet?

**Comment by simontaite** [comment]
Haven't worked on reverse engineer support in a while so will have to double check later when I get a chance but if it's not good for alpha it shouldn't take long to get it there

**Comment by simontaite** [comment]
@bricelam 
Looking into this at the moment and getting this error
`Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Scaffolding.ProviderCodeGenerator' while attempting to activate 'Bricelam.EntityFrameworkCore.FSharp.Scaffolding.FSharpDbContextGenerator'`

This is testing using Postgresql, a C# project performs the scaffold correctly

The issue appears to be here
https://github.com/aspnet/EntityFrameworkCore/blob/release/2.2/src/EFCore.Design/Design/Internal/DesignTimeServicesBuilder.cs#L89

Am I correct that currently EF Core will only load one instance of `IDesignTimeServices`?

**Comment by bricelam** [comment]
One from the user’s startup assembly. There can be multiple registered via DesignTimeServicesReferenceAttribute. The msbuild script adds this attribute to the startup project.

**Comment by simontaite** [comment]
Was able to scaffold the Northwind database without issue
At this stage I feel an alpha release can be justified

Caveats
#20 - generated files are not added to the project by default
#21 - many-types-per-table relationships are not currently supported

While #20 would not necessarily block an **alpha** release it is definitely something to be addressed soon as it is a major usability issue. We should not have to leave it up to the user to figure out the compilation order

Have created #23 to merge these changes

**Comment by simontaite** [comment]
Initial support added
Everything from here on will be a new ticket
