### ISSUE TITLE
Nullable needed on some column parameters

### ISSUE THREAD

**Issue by ahartman00** [bricelam/EFCore.FSharp#30]
When creating a column, the unicode, maxLength, and fixedLength parameters need to be wrapped in Nullable().  I am generating migrations for sqlite.

Column: `member val Gloss:string = "" with get, set`
Example before:  `table.Column<string>(unicode = false)`
after:  `table.Column<string>(unicode = Nullable(false))`

**Comment by simontaite** [comment]
Closed by #33 
Nullable values now written as `table.Column<string>(unicode = Nullable(false))`
