### ISSUE TITLE
Type is a reserved word in F#

### ISSUE THREAD

**Issue by ahartman00** [bricelam/EFCore.FSharp#31]
When generating migrations for sqlite, some columns have a "type" parameter.  Since the function is called using named parameters, you end up with: `table.Column<decimal>(nullable = false,type = "decimal(10, 0)", defaultValueSql = "('0')")`.  This generates a FS0010: Incomplete structured construct error, since type is a reserved keyword.

The only thing I can think of is just to call the function with all arguments.  Per MSDN, "Note that for nullable parameters a null value means not-specified".  However when I pass nulls for the arguments I didnt need, I get a "no overloads match" error.  So I had to come up with values.

Column: `member val SynsetId:decimal = 0.0m with get, set`
Generated: `table.Column<decimal>(nullable = false,type = "decimal(10, 0)", defaultValueSql = "('0')")`
No overloads match: `synset_id = table.Column<decimal>("decimal(10, 0)", null, null, false, "synset_id", false, null, null, null) `
Compiles:  `table.Column<decimal>("decimal(10, 0)", Nullable(false), Nullable(10), false, "synset_id", false, "('0')", "('0')", "('0')")`

**Comment by Tarmil** [comment]
You can escape identifiers by wrapping them in double backticks:

```fsharp
table.Column<decimal>(nullable = false, ``type`` = "decimal(10, 0)", defaultValueSql = "('0')")
```

**Comment by simontaite** [comment]
Have added a check when writing the parameter name that will wrap it in double backticks if it is an F# keyword
