### ISSUE TITLE
Version 1.0 or 2.1?

### ISSUE THREAD

**Issue by bricelam** [bricelam/EFCore.FSharp#5]
Should this package start at version 1.0.0 or should the version somehow indicate that it's compatible with EF Core 2.1+

**Comment by simontaite** [comment]
I feel it would make more sense for a package version of 2.1 to be in line with EF Core
It's one less bit of mental gymnastics to have to do when looking at versions, especially in the future when upgrading to 2.2 and beyond

**Comment by bricelam** [comment]
Agree we should go with aligning to EF since this package will likely need to change with every new EF release.
