### ISSUE TITLE
Travis build

### ISSUE THREAD

**Issue by simontaite** [bricelam/EFCore.FSharp#9]
Set up Travis build and configure config

**Comment by simontaite** [comment]
@bricelam 
https://travis-ci.org/bricelam/EFCore.FSharp can only be enabled by an owner/admin

**Comment by bricelam** [comment]
Activated.

**Comment by simontaite** [comment]
Created https://travis-ci.org/bricelam/EFCore.FSharp
It is however blocked by #6

**Comment by bricelam** [comment]
This should be good now once we add the `.travis.yml` file. We may also need to add the following to the *.fsproj file:
``` xml
<PublicSign Condition="'$(OS)' != 'Windows_NT'">True</PublicSign>
```
